name: build

on:
  schedule:
    - cron: '12 8 * * *'  # daily at 8:12 UTC

  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Create cache key for RB tables
        id: cachekey
        run: |
          set -xeu
          KEY="RB Tables $(curl -Is https://cdn.rebrickable.com/media/downloads/parts.csv.gz \
            | grep -iPo '^last-modified:\s*\K[^\r]+' \
            | tr -d , \
            || date --utc "+%Y%m%d%H")"
          echo "key=${KEY}" >> $GITHUB_OUTPUT

      - name: Set up cache for RB tables
        uses: actions/cache@v4
        with:
          path: data/*.csv
          key: ${{ steps.cachekey.outputs.key }}

      - name: Build database
        run: bash -x build.sh && ls -l data

      - name: Generate database dump hash
        id: generate-hash
        run: |
          set -xeu
          cd data
          sqlite3 rb.db .dump > rb.dump
          REGEX="INSERT INTO rb_db_lov VALUES\('data_timestamp','\d+'\);"
          grep -qPx "$REGEX" rb.dump
          grep -vPx "$REGEX" rb.dump | sha256sum | cut -d\  -f1 > rb.dump.sha256
          echo "sha256=$(cat rb.dump.sha256)" >> $GITHUB_OUTPUT

      - name: Cache database dump hash
        id: hash
        uses: actions/cache@v4
        with:
          path: data/rb.dump.sha256
          key: SQL Dump Hash ${{ steps.generate-hash.outputs.sha256 }}

      - name: Cancel this run
        if: steps.hash.outputs.cache-hit == 'true'
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.actions.cancelWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
      # Separate wait step to ensure correct reporting on previous step's success or failure
      - name: Wait for workflow to cancel
        if: steps.hash.outputs.cache-hit == 'true'
        uses: actions/github-script@v8
        with:
          script: |
            const delay = ms => new Promise(res => setTimeout(res, ms));
            while (true) {
              core.info('Waiting for workflow to cancel ...');
              await delay(5000);
            }

      - uses: actions/upload-artifact@v4
        with:
          name: rb.db
          path: data/rb.db
