name: build

on:
  push:
    branches:
      - master
    paths:
      - 'build/*'
      - 'schema/*'
      - 'build.sh'

  workflow_dispatch:

  workflow_call:

permissions:
  actions: write
  contents: write

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Create cache key for RB tables
        id: cachekey
        run: |
          set -xeu
          KEY="RB Tables $(curl -Is https://cdn.rebrickable.com/media/downloads/parts.csv.gz \
            | grep -iPo '^last-modified:\s*\K[^\r]+' \
            | tr -d , \
            || date --utc "+%Y%m%d%H")"
          echo "key=${KEY}" >> $GITHUB_OUTPUT

      - name: Set up cache for RB tables
        uses: actions/cache@v4
        with:
          path: data/*.csv
          key: ${{ steps.cachekey.outputs.key }}

      - name: Build database
        run: bash -x build.sh && ls -l data

      - name: Generate database dump hash
        id: generate-hash
        run: |
          set -xeu
          cd data
          sqlite3 rb.db .dump > rb.dump
          REGEX="INSERT INTO rb_db_lov VALUES\('data_timestamp','\d+'\);"
          grep -qPx "$REGEX" rb.dump
          grep -vPx "$REGEX" rb.dump | sha256sum | cut -d\  -f1 > rb.dump.sha256
          echo "sha256=$(cat rb.dump.sha256)" >> $GITHUB_OUTPUT

      - name: Cache database dump hash
        id: hash
        uses: actions/cache@v4
        with:
          path: data/rb.dump.sha256
          key: SQL Dump Hash ${{ steps.generate-hash.outputs.sha256 }}

      - name: Prepare release files
        if: steps.hash.outputs.cache-hit != 'true'
        run: |
          set -xeu
          cd data
          shasum -a256 rb.db > rb.db.sha256
          xz -k rb.db
          gzip -k rb.db
          zip rb.db.zip rb.db

      - name: Create release
        if: steps.hash.outputs.cache-hit != 'true'
        run: bash -x utils/create_release.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Unlike other steps, this one needs PAT since GITHUB_TOKEN cannot trigger
      # other workflows. So this step is made optional to simplify forking.
      - name: Deploy site
        if: steps.hash.outputs.cache-hit != 'true' && env.GH_TOKEN != ''
        run: |
          set -xeu
          WORKFLOW_ID="$(gh workflow list | grep -Poi 'site.+\s\K\d+$')"
          gh workflow run "$WORKFLOW_ID"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Prune old releases
        if: steps.hash.outputs.cache-hit != 'true'
        run: bash -x utils/prune_old_releases.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prune old caches
        if: steps.hash.outputs.cache-hit != 'true'
        run: |
          set -xeu
          NKEEP=5
          gh cache list --json id --jq ".[].id" | tail -n+$((NKEEP+1)) | xargs -rn1 gh cache delete
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
